spring.application.name=springboot-demo

# Folder to save log files
logging.file.name=logs/housemate-backend.log

# Sets the level of information to be logged.
logging.level.org.springframework.web=DEBUG


# Creates a new log file every time the previous goes over 10MB and keeps a history of 30 days,
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
logging.logback.rollingpolicy.total-size-cap=1GB